ALTER SESSION SET CONTAINER = ORCLPDB;

ALTER DATABASE OPEN;

CREATE USER NEWUSER IDENTIFIED BY 1234;

GRANT ALL PRIVILEGES TO NEWUSER;

-- GRANT CREATE SESSION TO newuser;
-- GRANT CREATE TABLE TO newuser;
-- GRANT CREATE ANY PROCEDURE TO newuser;
-- GRANT CREATE SEQUENCE TO newuser;
-- GRANT CREATE SYNONYM TO myuser;

CREATE OR REPLACE PROCEDURE "NEWUSER"."REMOVE_BOOK"(p_bookid IN NUMBER)
AS
BEGIN
   DELETE FROM "NEWUSER"."BOOK" WHERE BOOK_ID = p_bookid;
END;